### ISSUE TITLE
make gif with PIL.GifImagePlugin

### ISSUE THREAD

**Issue by catafest** [wnyc/PIL#1]
I try to used the gif maker feature. I try also to use 
To converts an image to another mode, and returns the new image, by using:
`im = im.convert("P")` the result is:
`  File "make_gif.py", line 38, in makedelta
    for s in getheader(im) + getdata(im):
TypeError: can only concatenate tuple (not "list") to tuple`
basic is the same script gifmaker.py , I renamed with make_gif.py
This is the error I got:
`Traceback (most recent call last):
  File "make_gif.py", line 96, in <module>
    compress(sys.argv[1], sys.argv[2])
  File "make_gif.py", line 83, in compress
    makedelta(fp, seq)
  File "make_gif.py", line 38, in makedelta
    for s in getheader(im) + getdata(im):
  File "C:\Python27\lib\site-packages\PIL\GifImagePlugin.py", line 675, in getdata
    ImageFile._save(im, fp, [("gif", (0, 0)+im.size, 0, RAWMODE[im.mode])])
KeyError: 'RGB'`

**Comment by noslouch** [comment]
This repo has been long abandoned. Perhaps you'll have more luck with your Python imagine concerns by using Pillow: https://github.com/python-pillow/Pillow
